# basic config

name = "LineWorld1000x650"

debug = true
projection = "VAN_DER_GRINTEN_I"
wrapover = true

# units in mm
width = 1000
height = 650

offset_x = 0.0
offset_y = 60

tolerance = 0.1
tolerance_exclusion_zones = 0.5

crop = true
crop_offset_x = 500
crop_offset_y = 350
crop_width = 1000
crop_height = 500

inkscape_command = "/Applications/Inkscape.app/Contents/MacOS/inkscape"

[main]
db_connection = "postgresql+psycopg://localhost:5432/lineworld"

[layer.Elevation]

[layer.Contour]
elevation_anchors = [0, 500, 2000, 9000]
num_elevation_lines = 9

[layer.Contour2]
elevation_anchors = [0, 500, 2000, 9000]
num_elevation_lines = 21
geotiff_scaling_factor = 0.25
window_size_tpi = 21
window_size_smoothing_low = 21
window_size_smoothing_high = 51
taubin_smoothing_steps = 20
tolerance = 0.05
filter_min_area_map = 2.0

[layer.Coastlines]
hatching_distance = 1.5

[layer.Bathymetry]
elevation_anchors = [0, -11000]
num_elevation_lines = 15

[layer.BathymetryFlowlines]
layer_name = "BathymetryFlowlines"
num_tiles = 4
line_distance = [0.1, 3.0]
blur_angles_kernel_size = 25
blur_inclination_kernel_size = 10
blur_density_kernel_size = 25
line_distance_end_factor = 0.5
line_max_segments = 20

[layer.Grid]
latitude_line_dist = 20
longitude_line_dist = 20
font_size = 6

[layer.GridBathymetry]
exclude_buffer_distance = 0.5

[layer.GridLabels]
exclude_buffer_distance = 1.0

[layer.CitiesLabels]
font_size = 6
circle_radius = 1.0
offset_from_center = 10

[layer.Labels]
font_size = 6
exclude_buffer_distance = 1.0