# basic config

name = "LineWorldBasicConfig"

debug = false
projection = "VAN_DER_GRINTEN_I"
wrapover = true

# units in mm
width = 2000
height = 1500

offset_x = 0.0
offset_y = 170

tolerance = 0.1
tolerance_exclusion_zones = 0.5

crop = true
crop_offset_x = 500
crop_offset_y = 350
crop_width = 1000
crop_height = 500

inkscape_command="/Applications/Inkscape.app/Contents/MacOS/inkscape"

[main]
db_connection = "postgresql+psycopg://localhost:5432/lineworld"

[layer.Contour]
elevation_anchors = [0, 500, 2000, 9000]
num_elevation_lines = 24

[layer.Bathymetry]
elevation_anchors = [0, -11000]
num_elevation_lines = 15

[layer.BathymetryFlowlines]
line_distance = [0.4, 2.0]
blur_distance = true
blur_distance_kernel_size = 20
blur_angles = true
blur_angles_kernel_size = 25
blur_length = true
blur_length_kernel_size = 10
line_distance_end_factor = 0.8

[layer.CitiesLabels]
font_size = 6
circle_radius = 3

[layer.Grid]
latitude_line_dist = 20
longitude_line_dist = 20
bathymetry_exclude_buffer_distance = 0.8
labels_exclude_buffer_distance = 2.0
font_size = 5